#!/bin/sh -e

make -C libnl ALL_LIBS=libnl-tiny.a

# Don't bother compressing tiny man page.
sed 's@\(iw\.8\)\.gz@\1@' Makefile > _
mv -f _ Makefile

# This symbol is only available for NL 3.0.
sed '/NLA_PUT_S32/d' sar.c > _
mv -f _ sar.c

export CFLAGS="$CFLAGS -I./libnl/include -DCONFIG_LIBNL20 -D_GNU_SOURCE"
export LDFLAGS="$LDFLAGS -L./libnl -static"

make \
    SBINDIR=/usr/bin \
    NO_PKG_CONFIG=Y \
    LIBS=-lnl-tiny \
    install
