#!/bin/sh -e

cat > config.mk <<EOF
PREFIX      = /usr/lib/9base
MANPREFIX   = \${PREFIX}/share/man

VERSION     = 7
OBJTYPE     = x86_64

CFLAGS      += -c -I. -DPLAN9PORT -DPREFIX="\"\${PREFIX}\"" -fcommon
LDFLAGS     += -static

AR          = ar rc
CC          = cc
YACC        = ../yacc/9yacc
EOF

make
make install
