#!/bin/sh -e

patch -p1 < no-gumbo.patch
sed -e '33,48d' -e '266,295d' Makelists > _
mv -f _ Makelists

export CFLAGS="$CFLAGS -fPIC -DFZ_ENABLE_HTML=0 -DFZ_ENABLE_EPUB=0 -DFZ_ENABLE_JPX=0 -DFZ_ENABLE_ICC=0"

rm -rf thirdparty/openjpeg

make \
    prefix=/usr \
    USE_SYSTEM_LIBS=yes \
    USE_SYSTEM_OPENJPEG=no \
    HAVE_X11=no \
    HAVE_GLUT=no \
    install
