#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

# fix CFLAGS
# -D_GNU_SOURCE is needed for IPv6 to work apparently
export CFLAGS="$CFLAGS -D_GNU_SOURCE"
sed -i "s:-O2 -pipe -Wall -g:${CFLAGS}:" pppd/Makefile.linux
sed -i "s:-g -O2:${CFLAGS}:" pppd/plugins/Makefile.linux
sed -i "s:-O2:${CFLAGS}:" pppstats/Makefile.linux
sed -i "s:-O2 -g -pipe:${CFLAGS}:" chat/Makefile.linux
sed -i "s:-O:${CFLAGS}:" pppdump/Makefile.linux
# enable active filter
sed -i "s:^#FILTER=y:FILTER=y:" pppd/Makefile.linux
# enable ipv6 support
sed -i "s:^#HAVE_INET6=y:HAVE_INET6=y:" pppd/Makefile.linux
# Enable Microsoft proprietary Callback Control Protocol
sed -i "s:^#CBCP=y:CBCP=y:" pppd/Makefile.linux
sed -i "s:^#CBCP=y:CBCP=y:" pppd/Makefile.linux
sed -i "s:^#USE_CRYPT=y:USE_CRYPT=y:" pppd/Makefile.linux

./configure \
    --prefix=/usr \
    --localstatedir=/var

make COPTS="$CFLAGS"
make INSTROOT="$1" install

install -Dm644 include/net/ppp_defs.h \
    "$1"/usr/include/net/ppp_defs.h
#install -D -m755 "$srcdir"/ip-up "$pkgdir"/etc/ppp/ip-up
#install -D -m755 "$srcdir"/ip-down "$pkgdir"/etc/ppp/ip-down
#install -D -m755 "$srcdir"/pppd.initd "$pkgdir"/etc/init.d/pppd
install -D -m644 etc.ppp/options      "$1"/etc/ppp/options
install -D -m600 etc.ppp/pap-secrets  "$1"/etc/ppp/pap-secrets
install -D -m600 etc.ppp/chap-secrets "$1"/etc/ppp/chap-secrets

# busybox ifup/ifdown needs pon/poff
install -D -m644 scripts/pon.1 "$1"/usr/share/man/man1/pon.1
install -D -m755 scripts/pon   "$1"/usr/bin/pon
install -D -m755 scripts/poff  "$1"/usr/bin/poff

install -d "$1"/usr/share/doc/ppp
for i in scripts/*; do
    case $i in
    pon|poff|*.1) continue;
    esac
    if [ -f "$i" ]; then
        cp "$i" "$1"/usr/share/doc/ppp/
    fi
done
install -d "$1"/etc/ppp/peers
