#!/bin/sh -e

patch -p1 < netbsd-curses_tic.patch

meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=fcft,tllist \
    -Dime=false \
    -Dthemes=false \
    . output

mkdir -p output/f
ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/zsh" \
    "$1/usr/share/fish" \
    "$1/usr/share/bash-completion"
