#!/bin/sh -e

unset DESTDIR

cp -ar openblas openblas-ilp64

mk() {
    make \
        PREFIX=/usr \
        NO_STATIC=1 \
        MAJOR_VERSION=3 \
        NO_AFFINITY=1 \
        NUM_THREADS="$(nproc)" \
        "$@"
}

mk -C openblas
mk -C openblas-ilp64 \
    INTERFACE64=1 \
    SYMBOLSUFFIX=64_

mk -C openblas \
    DESTDIR="$1" \
    install
mk -C openblas-ilp64 \
    DESTDIR="$1" \
    INTERFACE64=1 \
    SYMBOLSUFFIX=64_ \
    install
