#!/bin/sh -e

sed 's/set(COMPILER_RT_HAS_SANITIZER_COMMON TRUE)/set(COMPILER_RT_HAS_SANITIZER_COMMON FALSE)/' cmake/config-ix.cmake > _
mv -f _ cmake/config-ix.cmake

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCOMPILER_RT_BUILD_XRAY=OFF

cmake --build   build
cmake --install build

cd "$1"
mkdir -p usr/lib/clang/$2/lib
mv usr/lib/linux usr/lib/clang/$2/lib
