#!/bin/sh -e

ed scipy/optimize/rectangular_lsap/rectangular_lsap.cpp >/dev/null <<EOF
/vector/a
#include <stdint.h>
.
w
q
EOF

cat > site.cfg <<EOF
[ALL]
library_dirs = /usr/lib
include_dirs = /usr/include
EOF

export NPY_NUM_BUILD_JOBS="$(nproc)"
export NPY_USE_BLAS_ILP64=1

python setup.py build
python setup.py install \
    --prefix=/usr \
    --root="$1" \
    --optimize=1
