#!/bin/sh -e

export CFLAGS="$CFLAGS -fplt"
export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

patch -p1 < rootless_modesetting.patch

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --disable-systemd-logind \
    --enable-xorg \
    --disable-xvfb \
    --disable-xnest \
    --disable-unit-tests \
    --without-systemd-daemon

make
make install
