#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dvalgrind=disabled \
    -Damdgpu=disabled \
    -Dnouveau=disabled \
    -Dradeon=disabled \
    -Dintel=disabled \
    build

ninja -C build
muon  -C build install
