#!/bin/sh -e

mkdir build inst

cd build
CFLAGS="$CFLAGS -D_PR_POLL_AVAILABLE -D_PR_HAVE_OFF64_T -D_PR_INET6 -D_PR_HAVE_INET_NTOP -D_PR_HAVE_GETHOSTBYNAME2 -D_PR_HAVE_GETADDRINFO -D_PR_INET6_PROBE" \
../nspr/configure \
    --prefix=/usr \
    --disable-debug \
    --enable-optimize \
    --enable-64bit

make
make install

rm -f -- "$1"/usr/lib/*.a
rm -rf "$1"/usr/bin/prerr.properties \
    "$1"/usr/bin/compile-et.pl \
    "$1"/usr/share \
    "$1"/usr/include/nspr/md
