#!/bin/sh -e

unset DESTDIR

autoreconf -fiv
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man

make

mkdir -p \
    "$1"/etc/urlview \
    "$1"/usr/share/man/man1 \
    "$1"/usr/bin

make prefix="$1/usr" mandir="$1/usr/share/man" install

install -Dm755 url_handler.sh "$1"/etc/urlview/url_handler.sh
install -Dm644 sample.urlview "$1"/etc/urlview/system.urlview
ln -fs /etc/urlview/url_handler.sh "$1"/usr/bin/url_handler.sh
