#!/bin/sh -e

patch -p1 < r4s.patch
patch -p1 < rockpro64.patch

unset CFLAGS CXXFLAGS

sed 's/\-lgcc//g' Makefile > _
mv -f _ Makefile

for board in nanopi-r4s-rk3399 rockpro64-rk3399; do
    mkdir -p "build/$board"

    make O="build/$board" "${board}_defconfig"
    make \
        CROSS_COMPILE=aarch64-linux-musl- \
        BL31=$KISS_ROOT/usr/share/atf/rk3399/bl31.elf \
        O="build/$board"

    mkdir -p "$1/usr/share/u-boot/$board"

    cp "build/$board/u-boot.itb"    "$1/usr/share/u-boot/$board/"
    cp "build/$board/idbloader.img" "$1/usr/share/u-boot/$board/"
done
