#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_AOM_DECODER=OFF \
    -DWITH_AOM_DECODER_PLUGIN=OFF \
    -DWITH_AOM_ENCODER=OFF \
    -DWITH_AOM_ENCODER_PLUGIN=OFF

cmake --build   build
cmake --install build
