#!/bin/sh -e

meson \
    --prefix=/usr \
    -Dipv6=true \
    -Dxvfb=false \
    -Dxdmcp=false \
    -Dxcsecurity=true \
    -Ddri3=true \
    -Dxwayland_eglstream=false \
    -Dglamor=true \
    -Dxkb_dir=/usr/share/X11/xkb \
    -Dxkb_output_dir=/var/lib/xkb \
    . output

ninja -C output
ninja -C output install
