#!/bin/sh -e

cat > site.cfg << EOF
[openblas_ilp64]
libraries = openblas
library_dirs = /usr/lib
include_dirs = /usr/include
runtime_library_dirs = /usr/lib
EOF

export NPY_USE_BLAS_ILP64=1
export NPY_BLAS_ILP64_ORDER=openblas_ilp64
export NPY_LAPACK_ILP64_ORDER=openblas_ilp64

python setup.py build
python setup.py install \
    --prefix=/usr \
    --root="$1" \
    --optimize=1
