#!/bin/sh -e

cat > site.cfg <<EOF
[openblas64_]
libraries = openblas64_
library_dirs = /usr/lib
include_dirs = /usr/include
runtime_library_dirs = /usr/lib
EOF

export NPY_USE_BLAS_ILP64=1
export NPY_BLAS_ILP64_ORDER=openblas64_
export NPY_LAPACK_ILP64_ORDER=openblas64_

python setup.py build \
    -j "$(nproc)"
python setup.py install \
    --prefix=/usr \
    --root="$1" \
    --optimize=1
