#!/bin/sh -e

export CFLAGS="$CFLAGS -DSMALL"

./configure \
    --prefix=/usr \
    --disable-curses \
    --enable-ksh \
    --enable-lto \
    --enable-static

#echo '#undef EMACS' >> pconfig.h

make
make install
