#!/bin/sh -e

ed configure <<EOF
,s/-lcurses/-lcurses -lterminfo/
w
q
EOF

./configure \
    --prefix=/usr \
    --enable-ksh \
    --enable-static

echo '#undef EMACS' >> pconfig.h

make
make install
