#!/bin/sh -e

export CFLAGS="$CFLAGS -O3"

#cp -pR fftw fftw-single
#cp -pR fftw fftw-long-double
#cp -pR fftw fftw-quad

#(
#    cd fftw-single
#
#    ./configure \
#        --prefix=/usr \
#        --enable-shared \
#        --enable-threads \
#        --enable-sse \
#        --enable-avx \
#        --enable-single
#)

(
    cd fftw

    ./configure \
        --prefix=/usr \
        --enable-shared \
        --disable-static \
        --disable-fortran \
        --enable-sse2 \
        --enable-avx2 \
        --enable-avx512
)

#(
#    cd fftw-long-double
#
#    ./configure \
#        --prefix=/usr \
#        --enable-shared \
#        --enable-threads \
#        --enable-long-double
#)
#
#(
#    cd fftw-quad
#
#    ./configure \
#        --prefix=/usr \
#        --enable-shared \
#        --enable-threads \
#        --enable-quad-precision
#)

#make -C fftw-single
make -C fftw
#make -C fftw-long-double
#make -C fftw-quad

#make install -C fftw-single
make install -C fftw
#make install -C fftw-long-double
#make install -C fftw-quad
