#!/bin/sh -e

patch -p1 < add-av_stream_get_first_dts-for-chromium.patch
patch -p1 < binutils-2.41.patch

./configure \
    --cc="$CC" \
    --cxx="$CXX" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --disable-static \
    --disable-libxcb \
    --disable-libxcb-shm \
    --disable-libxcb-xfixes \
    --disable-libxcb-shape \
    --disable-xlib \
    --enable-gpl \
    --enable-libaom \
    --enable-libass \
    --enable-libdav1d \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-nonfree \
    --enable-libtls \
    --enable-shared \
    --enable-version3 \
    --x86asmexe=nasm

make
make install

rm -rf "$1/usr/share/ffmpeg/examples"
