#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dalsa=enabled \
    -Dwayland=enabled \
    -Dx11=disabled \
    output

ninja -C output
muon  -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
