#!/bin/sh -e

_target=aarch64-linux-musl

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

./configure \
    --prefix=/usr \
    --program-prefix="$_target"- \
    --target="$_target" \
    --enable-deterministic-archives \
    --enable-multiarch \
    --disable-gold \
    --disable-lto \
    --enable-ld=default \
    --enable-plugins \
    --disable-multilib \
    --disable-werror \
    --disable-gdb \
    --disable-nls \
    --disable-readline \
    --disable-gprof \
    --disable-gprofng \
    --with-mmap \
    --with-system-zlib

make configure-host
make tooldir=/usr
make DESTDIR="$1" tooldir=/usr install

rm -Rf $1/usr/lib/bfd-plugins
rm -Rf $1/usr/share/info

for prog in strip readelf ranlib objdump objcopy nm ld ld.bfd as ar
do
    rm -f $1/usr/bin/$prog
done
