#!/bin/sh -e

meson \
  -Dprefix=/usr \
  -Dasm=enabled \
  -Dx11=disabled \
  -Degl=true \
  -Dglx=disabled \
  -Dgles1=true \
  -Dgles2=true \
  -Dtls=disabled \
  -Dheaders=true \
  -Dentrypoint-patching=enabled \
  . output

ninja -C output
ninja -C output install
