#!/bin/sh -e

patch -p1 < curses.patch

./configure \
    prefix=/usr \
    CONFIG_CUE=n \
    CONFIG_FFMPEG=n \
    CONFIG_FLAC=y \
    CONFIG_MAD=y \
    CONFIG_OPUS=y \
    CONFIG_OSS=n

make
make install
