#!/bin/sh -e

./configure \
    --prefix=/usr \
    --exec-prefix=/usr \
    --disable-systemd \
    --enable-library \
    --disable-obex \
    --mandir=/usr/share/man \
    --with-udevdir=/etc/udev \
    --disable-manpages

make
make install

install -Dm755 bluetoothd.run "$1/etc/sv/bluetoothd/run"
ln -s /run/runit/supervise.bluetoothd "$1/etc/sv/bluetoothd/supervise"
