#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --disable-systemd \
    --enable-library \
    --disable-manpages \
    --disable-obex \
    --with-udevdir=/etc/udev

make
make install

install -Dm755 bluetoothd.run "$1/etc/sv/bluetoothd/run"
ln -s /run/runit/supervise.bluetoothd "$1/etc/sv/bluetoothd/supervise"
