#!/bin/sh -e

for f in init str client server; do
    echo cc $CFLAGS -fPIC -c "xoauth2_$f.c"
    cc $CFLAGS -fPIC -c "xoauth2_$f.c"
done

echo cc -shared -fPIC xoauth2_init.o xoauth2_str.o xoauth2_client.o \
    xoauth2_server.o $CFLAGS $LDFLAGS -Wl,-soname -Wl,libxoauth2.so.0 -o \
    libxoauth2.so.0.0.0
cc -shared -fPIC xoauth2_init.o xoauth2_str.o xoauth2_client.o \
    xoauth2_server.o $CFLAGS $LDFLAGS -Wl,-soname -Wl,libxoauth2.so.0 -o \
    libxoauth2.so.0.0.0

mkdir -p "$1/usr/lib/sasl2"
cp libxoauth2.so.0.0.0 "$1/usr/lib/sasl2/"
ln -s libxoauth2.so.0.0.0 "$1/usr/lib/sasl2/libxoauth2.so.0"
ln -s libxoauth2.so.0.0.0 "$1/usr/lib/sasl2/libxoauth2.so"
