#!/bin/sh -e

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_BOOST=OFF \
    -DENABLE_CPP=ON \
    -DENABLE_GOBJECT_INTROSPECTION=OFF \
    -DENABLE_LIBOPENJPEG=none \
    -DENABLE_QT5=OFF \
    -DENABLE_QT6=OFF \
    -DWITH_NSS3=OFF

cmake --build   build
cmake --install build
