#!/bin/sh -e

patch -p1 <<EOF
--- a/mutt_curses.h
+++ b/mutt_curses.h
@@ -52,6 +52,10 @@
 # include <curses.h>
 #endif

+// #include <term.h> - can't include term.h, because it defines macro columns which clashes
+// with variable name used in mutt, so just define the prototype for tigetstr()
+char *tigetstr(const char *capname);
+
 #define MUTT_ENTER_C '\n'
 #define MUTT_ENTER_S "\n"

EOF

# Remove perl dependency.
sed 's/ doc contrib/ contrib/g' Makefile.in > _
mv -f _ Makefile.in

./configure \
    LIBS=-lterminfo \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-doc \
    --disable-full-doc \
    --enable-hcache

make
make install-exec

rm -f "$1/etc/mime.types"

mkdir -p \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5" \

# Install manual pages.
for file in \
    mutt.1 pgpring.1 pgpewrap.1 smime_keys.1 mbox.5 mmdf.5 muttrc.5
do
    base=${file%%.[15]}
    suf=${file##"$base".}

    sed \
        -e 's,@docdir@,/usr/share/doc,g' \
        -e 's,@sysconfdir@,/etc,g' \
        -e 's,@bindir@,/usr/bin,g' \
        "doc/$base.man" > "$1/usr/share/man/man$suf/$file"
done
