#!/bin/sh -e

patch -p1 <<EOF
--- a/color.c
+++ b/color.c
@@ -133,9 +133,8 @@ static const struct mapping_t ComposeFields[] =

 #define COLOR_QUOTE_INIT	8

-#ifdef NCURSES_VERSION
 #define ATTR_MASK (A_ATTRIBUTES ^ A_COLOR)
-#elif defined (USE_SLANG_CURSES)
+#if defined (USE_SLANG_CURSES)
 #define ATTR_MASK (~(unsigned int)A_NORMAL ^ (A_CHARTEXT | A_UNUSED | A_COLOR))
 #endif
EOF

# Remove perl dependency.
sed 's/ doc contrib/ contrib/g' Makefile.in > _
mv -f _ Makefile.in

./configure \
    LIBS=-lterminfo \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-doc \
    --disable-full-doc \
    --enable-hcache

make
make install-exec

rm -f "$1/etc/mime.types"

mkdir -p \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5" \

# Install manual pages.
for file in \
    mutt.1 pgpring.1 pgpewrap.1 smime_keys.1 mbox.5 mmdf.5 muttrc.5
do
    base=${file%%.[15]}
    suf=${file##"$base".}

    sed \
        -e 's,@docdir@,/usr/share/doc,g' \
        -e 's,@sysconfdir@,/etc,g' \
        -e 's,@bindir@,/usr/bin,g' \
        "doc/$base.man" > "$1/usr/share/man/man$suf/$file"
done
