#!/bin/sh -e

make ALL_LIBS=libnl-tiny.a -C libnl

export PKG_CONFIG_PATH="$PWD/libnl:$PKG_CONFIG_PATH"
export CFLAGS="$CFLAGS -I$PWD/libnl/include -D_GNU_SOURCE"
export LDFLAGS="$LDFLAGS -static -L$PWD/libnl"

make \
    NL1FOUND="" NL2FOUND=Y NLLIBNAME=libnl-tiny LIBS=-lnl-tiny \
    PREFIX=/usr \
    SBINDIR=/usr/bin \
    install

pigz -d < "$1/usr/share/man/man8/iw.8.gz" > "$1/usr/share/man/man8/iw.8"
rm "$1/usr/share/man/man8/iw.8.gz"
