#!/bin/sh -e

muon setup \
    -Dprefix=/usr \
    -Dsystem_pid_file=/run/dbus/dbus.pid \
    output

ninja -C output
muon  -C output install

mkdir -p "$1/etc/sv/dbus"
cp -f dbus.run "$1/etc/sv/dbus/run"
ln -s /run/runit/supervise.dbus "$1/etc/sv/dbus/supervise"
