#!/bin/sh -e

sip-build \
    --confirm-license \
    --no-make \
    --api-dir /usr/share/qt/qsci/api/python

make -C build
make -C build INSTALL_ROOT="$1" install

# Remove unused py2 version of uic modules:
rm -r "$1"/usr/lib/python*/site-packages/PyQt5/uic/port_v2

# compile Python bytecode
python -m    compileall -d / "$1"/usr/lib
python -O -m compileall -d / "$1"/usr/lib
