#!/bin/sh -e

[ "$WAYLAND_DISPLAY" ] || {
    printf 'error: foot-pgo requires a running wayland session\n' >&2
    exit 1
}

case $("$CC" --version) in
    *clang*)
        # Clang requires this for PGO.
        export CFLAGS="$CFLAGS -Wno-ignored-optimization-argument"
    ;;

    *GCC*)
        # PGO with < -O3 is slow > GCC 10.1.X.
        export CFLAGS="$CFLAGS -O3"
    ;;
esac

# Generate PGO data.
{
    muon setup \
        -Dprefix=/usr \
        -Dbuildtype=release \
        -Dime=false \
        -Db_pgo=generate \
        build

    ninja -C build
    muon  -C build test

    # Required (gives some profiling data).
    build/footclient --version

    set -- \
        scripts/generate-alt-random-writes.py \
        --scroll \
        --scroll-region \
        --colors-regular \
        --colors-bright \
        --colors-256 \
        --colors-rgb \
        --attr-bold \
        --attr-italic \
        --attr-underline \
        --sixel \
        .pgotmp

    build/foot \
        --config=/dev/null \
        --term=xterm \
        sh -c "$* && cat .pgotmp"
}

# Clang requires this for PGO.
case $("$CC" --version) in *clang*)
    llvm-profdata merge default_*profraw --output=build/default.profdata
esac

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dime=false \
    -Db_pgo=use \
    build

ninja -C build
muon  -C build install

rm -rf \
    "$DESTDIR/usr/share/doc" \
    "$DESTDIR/usr/share/zsh" \
    "$DESTDIR/usr/share/fish" \
    "$DESTDIR/usr/share/bash-completion"
