#!/bin/sh -e

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=wayland \
    -Dglx=disabled \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dvulkan-drivers='' \
    -Dgallium-drivers=iris \
    -Dllvm=disabled \
    output

ninja -C output
muon  -C output install
