#!/bin/sh -e

sed 's/POP3_BUFSIZE 1024/POP3_BUFSIZE 4096/' src/pop3.h > _
mv -f _ src/pop3.h

./configure \
    --prefix=/usr \
    --disable-nls \
    --with-tls=libtls \
    --without-mpopd

make
make install
