#!/bin/sh -e

patch -p1 < prevent-clobbering.patch

make
make PREFIX=/usr install

for libs in curses terminfo panel menu form; do
    chmod 755 "$1/usr/lib/lib${libs}.so"
done

rm -f \
    "$1/usr/lib/pkgconfig/ncursesw.pc" \
    "$1/usr/lib/libncursesw.a" \
    "$1/usr/lib/libncursesw.so"
