#!/bin/sh -e

export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

cargo build \
    --release \
    --locked \
    --no-default-features \
    --features native-zlib

mkdir -p "$1/usr/bin"
cp -f target/release/sccache "$1/usr/bin"
