#!/bin/sh -e

export CARGO_HOME=$PWD

export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
    done
)

mkdir -p .cargo

cat > .cargo/config <<EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

cargo build \
    --release \
    --frozen \
    --no-default-features \
    --features native-zlib

mkdir -p "$1/usr/bin"
cp -f target/release/sccache "$1/usr/bin"
