#!/bin/sh -e

build_freetype() (
    cd freetype

    meson \
        --prefix=/usr \
        -Ddefault_library=both \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        "$@" \
        . output

    ninja -C output
    ninja -C output install
)

build_graphite() (
    cd graphite

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_C_FLAGS:STRING="$CFLAGS" \
        -DCMAKE_BUILD_TYPE:STRING=None \
        -DGRAPHITE2_COMPARE_RENDERER=OFF \
        -DGRAPHITE2_NFILEFACE=ON

    cmake --build   build
    cmake --install build
)

build_harfbuzz() (
    cd harfbuzz

    meson \
        --prefix=/usr \
        -Dpkg_config_path="$DESTDIR/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dgraphite=enabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    ninja -C output
    ninja -C output install
)

# Point Freetype to the Harfbuzz files.
export CFLAGS="$CFLAGS -I$DESTDIR/usr/include/harfbuzz"
export CFLAGS="$CFLAGS -L$DESTDIR/usr/lib "
export PKG_CONFIG_PATH=$DESTDIR/usr/lib/pkgconfig

# Point Harfbuzz to the Freetype anad Graphite files.
export CXXFLAGS="$CXXFLAGS -I$DESTDIR/usr/include/freetype2 -I$DESTDIR/usr/include"
export CXXFLAGS="$CXXFLAGS -L$DESTDIR/usr/lib"

build_freetype -Dharfbuzz=disabled
build_graphite
build_harfbuzz
build_freetype -Dharfbuzz=enabled --reconfigure
