#!/bin/sh -e

cat > setup.cfg << EOF
[libs]
enable_lto = True
system_freetype = True

[rc_options]
backend = TkAgg
EOF

python setup.py build
python setup.py install \
    --root "$1" \
    --prefix=/usr \
    --optimize=1 \
    --skip-build
