#!/bin/sh -e

patch -p1 <<EOF
--- a/dirmngr/server.c
+++ b/dirmngr/server.c
@@ -2776,7 +2776,9 @@ cmd_ad_query (assuan_context_t ctx, char *line)

   if (opt_help)
     {
+#if USE_LDAP
       ks_ldap_help_variables (ctrl);
+#endif
       err = 0;
       goto leave;
     }
EOF

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/gnupg \
    --disable-gpgsm \
    --disable-scdaemon \
    --disable-keyboxd \
    --disable-doc \
    --disable-gpgtar \
    --disable-wks-tools \
    --disable-photo-viewers \
    --disable-card-support \
    --disable-ccid-driver \
    --disable-sqlite \
    --disable-gnutls \
    --disable-ldap \
    --disable-nls

make
make install
