#!/bin/sh -e

out=$PWD/out
mkdir -p out

(
    cd ntbtls

    ./configure \
        --prefix=/usr \
        --enable-static \
        --disable-shared

    make
    make DESTDIR="$out" install
)

export CPPFLAGS="$CPPFLAGS -I$out/usr/include"
export LDFLAGS="$LDFLAGS -L$out/usr/lib"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/gnupg \
    --disable-scdaemon \
    --disable-ldap \
    --disable-nls

make
make install
