#!/bin/sh -e

rm -rf expat jbig2dec jpeg lcms2mt libpng openjpeg tiff zlib
patch -Np1 < 2010_add_build_timestamp_setting.patch

sed "s/gscms_transformm_color_const/gscms_transform_color_const/" \
    base/gsicc_lcms2.c > _ ; mv -f _ base/gsicc_lcms2.c

./configure \
    --prefix=/usr \
    --disable-gtk \
    --disable-dbus \
    --with-drivers=ALL \
    --with-fontpaths=/usr/share/ghostscript/fonts/:/usr/share/fonts

make so all
make -j1 install-so install

rm -rf "$1/usr/share/man/de/"
