#!/bin/sh -e

d(){
    echo "$1" ; exit 1
}

# Check if wayland is installed.
kiss list wayland && {
    cf="--without-x"
}

# If libX11 is installed, then check for libXaw.
kiss list libX11 && {
    kiss list libXaw || d "-> libXaw not installed"
}

_luatex="dvilualatex dviluatex lualollipop lualatex"
_pdftex="amstex cslatex csplain eplain etex jadetex latex lollipop mex
    mllatex mltex pdfetex pdfcslatex pdfcsplain pdfjadetex pdflatex
    pdfmex pdfxmltex texsis utf8mex xmltex"
_xetex="xelatex xelollipop"
_dvi="afm2tfm bbox dvigif dvipng dvips epsffit extractres includeres
    ps2eps psbook psjoin psnup psresize psselect pstops"

mkdir -p build && cd build
../configure -C \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-biber \
    --enable-epsfwin \
    --enable-ipc \
    --enable-luatex \
    --enable-mftalkwin \
    --enable-regiswin \
    --enable-shared \
    --enable-tektronixwin \
    --enable-unitermwin \
    --enable-xetex \
    --enable-dvipng \
    --enable-dvipsk \
    --enable-ps2eps \
    --enable-psutils \
    --disable-bibtex-x \
    --disable-chktex \
    --disable-cjkutils \
    --disable-detex \
    --disable-dialog \
    --disable-dvi2tty \
    --disable-dvisvgm \
    --disable-largefile \
    --disable-lcdf-typetools \
    --disable-multiplatform \
    --disable-native-texlive-build \
    --disable-pdfopen \
    --disable-ps2pkm \
    --disable-t1utils \
    --disable-tex4htk \
    --disable-ttf2pk2 \
    --disable-vlna \
    --disable-xindy \
    --disable-xpdf-open \
    --with-ps=gs \
    --with-banner-add="/KISS Linux" \
    --with-system-cairo \
    --with-system-freetype2 \
    --with-system-gd \
    --with-system-gmp \
    --with-system-graphite2 \
    --with-system-harfbuzz \
    --with-system-icu \
    --with-system-libpng \
    --with-system-mpfr \
    --with-system-pixman \
    --with-system-poppler \
    --with-system-zlib \
    --with-system-zziplib \
    --without-texinfo \
    "$cf"

make
make DESTDIR="$1" install

for texcmd in $_pdftex; do
    ln -s pdftex "$1/usr/bin/$texcmd"
done
ln -s eptex "$1"/usr/bin/platex
ln -s euptex "$1"/usr/bin/uplatex

for texcmd in $_xetex; do
    ln -s xetex "$1/usr/bin/$texcmd"
done

for texcmd in $_luatex; do
    ln -s luatex "$1/usr/bin/$texcmd"
done

rm -rf "$1/usr/bin/tlmgr"
rm -rf "$1/usr/share/texmf-dist"
