#!/bin/sh -e

cat > config.mk <<EOF
CC                  = gcc
CFLAGS              ?= -pipe

ENABLE_DEBUG        = 0
ENABLE_STATIC       = 1
ENABLE_SHARED       = 1

ENABLE_PIXMAN       = 1
ENABLE_DRM          = 1
ENABLE_WAYLAND      = 1

DRM_DRIVERS         = intel
WAYLAND_INTERFACES  = shm

ifeq ($(ENABLE_DRM),1)
    WAYLAND_INTERFACES += drm
endif
EOF

patch -p1 < tgl_gt2.patch

make
make PREFIX=/usr install
