#!/bin/sh -e

cmake -B build . \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_TYPE=None \
	-DRAPIDJSON_BUILD_DOC=OFF \
	-DRAPIDJSON_BUILD_EXAMPLES=OFF \
	-DGTESTSRC_FOUND=ON \
	-DGTEST_SOURCE_DIR=.

cmake --build   build
cmake --install build
