#!/bin/sh -e

export CPPFLAGS="$CPPFLAGS -DDISABLE_ENGINES"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-html-manual

make
make install

mkdir -p "$1/etc/sv/tor"
cp -f tor.run "$1/etc/sv/tor/run"
ln -sf /run/runit/supervise.tor "$1/etc/sv/tor/supervise"
