#!/bin/sh -e

out=$PWD/out
mkdir -p out

(
    cd libcbor

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=False \
        -DCMAKE_BUILD_TYPE=None

    cmake --build build
    DESTDIR="$out" cmake --install build
)

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_STATIC_LIBS=False \
    -DCMAKE_BUILD_TYPE=None \
    -DCBOR_LIBRARY="$out/usr/lib/libcbor.a" \
    -DCBOR_INCLUDE_DIR="$out/usr/include"

cmake --build   build
cmake --install build
