#!/bin/sh -e

patch -p1 < no-execinfo.patch
patch -p1 < wayland.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DINSTALL_DRIVER_SYSCONF=OFF

cmake --build   build
cmake --install build
