#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --with-screen=ncursesw \
    --with-ssl \
    --with-zlib \
    --disable-finger \
    --disable-news \
    --disable-ftp \
    --disable-dired \
    --without-ssl

make
make install
