#!/bin/sh -e

meson \
    --prefix=/usr \
    -Dwindows=wayland \
    -Dman=disabled \
    -Dfreeimage=disabled \
    -Dlibtiff=enabled \
    -Dlibpng=enabled \
    -Dlibjpeg=enabled \
    -Dlibrsvg=disabled \
    -Dlibnsgif=disabled \
    -Dlibheif=disabled \
    . output

ninja -C output
ninja -C output install
